[tools]
codex = "0.141.0"
neovim = "0.12.3"
node = "24.16.0"
python = "3.14.6"
rust = { version = "1.96.0", profile = "default", components = "rust-analyzer" }
tree-sitter = "0.26.9"
usage = "3.5.0"
uv = "0.11.21"
